_BASE_: "../coco/r50_coco.yaml"
MODEL:
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 57
  ROI_BOX_HEAD:
    MULT_OBJECT_SCORE: True
    USE_SIGMOID_CE: True
    USE_ZEROSHOT_CLS: True
    ZEROSHOT_WEIGHT_DIM: 1024
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/pascal_part_base_clip_a+cname.npy'
    ZEROSHOT_WEIGHT_INFERENCE_PATH: 'datasets/metadata/pascal_part_clip_a+cname.npy'
DATASETS:
  TRAIN: ("pascal_part_base_train",)
  TEST: ("pascal_part_val",)
SOLVER:
  IMS_PER_BATCH: 16
  USE_CUSTOM_SOLVER: True
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.00005
  STEPS: (6000, 8000)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 2000
TEST:
  DETECTIONS_PER_IMAGE: 100
  EVAL_PERIOD: 2000