_BASE_: "../coco/r50_coco.yaml"
MODEL:
  WEIGHTS: 'models/r50_lvis.pth'
  ROI_HEADS:
    NUM_CLASSES: 1203 # max of num_classes in all train datasets
    SCORE_THRESH_TEST: 0.0001
  ROI_BOX_HEAD:
    MULT_OBJECT_SCORE: True
    USE_SIGMOID_CE: True
    USE_ZEROSHOT_CLS: True
    USE_ZEROSHOT_CLS_GROUP: True
    ZEROSHOT_WEIGHT_DIM: 1024
    ZEROSHOT_WEIGHT_PATH_GROUP: [
      'datasets/metadata/lvis_v1_clip_RN50_a+cname.npy',
      'datasets/metadata/lvis_v1_clip_RN50_a+cname.npy',
    ]
    ZEROSHOT_WEIGHT_INFERENCE_PATH: 'datasets/metadata/lvis_v1_clip_RN50_a+cname.npy'
    IGNORE_ZERO_CATS_GROUP: [False, False]
    USE_FED_LOSS_GROUP: [True, False]
    CAT_FREQ_PATH_GROUP: [
      'datasets/metadata/lvis_v1_train_cat_info.json',
      '',
    ]
DATASETS:
  TRAIN: ("lvis_v1_train", "imagenet_lvis_v1")
  TEST: ("lvis_v1_minival",)
SOLVER:
  IMS_PER_BATCH: 16
  USE_CUSTOM_SOLVER: True
  OPTIMIZER: "ADAMW"
  BASE_LR: 0.00005
  STEPS: (20000, 25000)
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 5000
TEST:
  DETECTIONS_PER_IMAGE: 300
  EVAL_PERIOD: 10000
INPUT:
  CUSTOM_AUG: ResizeShortestEdge
  MIN_SIZE_TRAIN_SAMPLING: range
  MIN_SIZE_TRAIN: (640, 800)
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 4]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [2, 8]
  USE_RFS: [True, False]
  DATASET_MIN_SIZES: [[640, 800], [400, 400]]
  DATASET_MAX_SIZES: [1333, 667]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'image']
  NUM_WORKERS: 8
WITH_IMAGE_LABELS: True