MODEL:
  ANN_GENERATOR: True
  META_ARCHITECTURE: ParserNet
  PIXEL_NORM: True
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
DINO:
  MODEL_TYPE: 'vit_small_patch16_224'
  STRIDE: 8
  LAYER: 11
  BUILD_BASEDATA: True
  BASEDATA_SAVE_DIR: "output_basedata_pascalpartbase_vit"
DATASETS:
  TEST: ("pascal_part_base_train_one",)
INPUT:
  MIN_SIZE_TEST: 336
  MAX_SIZE_TEST: 996
  FORMAT: "RGB"
DATALOADER:
  NUM_WORKERS: 4
VERSION: 2
OUTPUT_DIR: "output/ClusterDet/auto"
