MODEL:
  ANN_GENERATOR: True
  META_ARCHITECTURE: ParserNet
  PIXEL_NORM: True
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
DINO:
  MODEL_TYPE: 'dino_vits8'
  STRIDE: 8
  LAYER: 11
  THRESH: 0.05
  BUILD_BASEDATA: False
  BASEDATA_SAVE_DIR: 'output_basedata_pascalpart'
  BASEDATA_ANN_PATH: 'datasets/pascal_part/train_one.json'
  BASEDATA_IMS_PATH: 'datasets/pascal_part/VOCdevkit/VOC2010/JPEGImages/'
DATASETS:
  TEST: ("partimagenet_supercat",)
OUTPUT_ANN_DIR: 'datasets/partimagenet/partimagenet_parsed.json'
INPUT:
  MIN_SIZE_TEST: 336
  MAX_SIZE_TEST: 996
  FORMAT: "RGB"
DATALOADER:
  NUM_WORKERS: 4
VERSION: 2
OUTPUT_DIR: "output/ClusterDet/auto"
